name: Unit Test

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode debug google-services.json
        env:
          FIREBASE_SECRET_DEBUG: ${{ secrets.FIREBASE_GOOGLE_SERVICE_DEBUG }}
        run: echo $FIREBASE_SECRET_DEBUG > app/src/debug/google-services.json
      - name: Decode release google-services.json
        env:
          FIREBASE_SECRET_RELEASE: ${{ secrets.FIREBASE_GOOGLE_SERVICE_RELEASE }}
        run: echo $FIREBASE_SECRET_RELEASE > app/src/release/google-services.json
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test --stacktrace
